### ISSUE TITLE
Error storing dataframe in SQLite database [length(dbname) == 1 is not TRUE]

### ISSUE THREAD

**Issue by zizekw** [girke-lab/drugbankR#1]
Hi, great work on this package. I have limited experience with XML + SQLite so this was perfect for me. Have ran into an error that I'm not sure how to approach.

> df2SQLite(dbdf=drugbank_dataframe, version)
Error in .local(drv, ...) : length(dbname) == 1 is not TRUE

> traceback()
6: stop(simpleError(msg, call = sys.call(-1)))
5: stopifnot(length(dbname) == 1, !is.na(dbname))
4: .local(drv, ...)
3: dbConnect(SQLite(), paste0(ext_path, "/drugbank_", version, ".db"))
2: dbConnect(SQLite(), paste0(ext_path, "/drugbank_", version, ".db"))
1: df2SQLite(dbdf = drugbank_dataframe, version)

Any suggestions? Thanks!

**Comment by yduan004** [comment]
Hi, I am so sorry that I just saw your issue yesterday. I have updated the package and README. If you are still interested, please follow the new README instructions to build the DrugBank SQLite database locally and query it. If you run into any problems, please feel free to ask me. I appreciate your interest and efforts to this package. Thanks! @zizekw 

Yuzhu

**Comment by zizekw** [comment]
Works like a charm now! Thank you so much.
