### ISSUE TITLE
Issues with library(drugbankR)

### ISSUE THREAD

**Issue by sookwah-yee** [girke-lab/drugbankR#4]
Hi, what should I do with the error below?  I cannot continue to try out your code.  Can you let me know what should I do from the error below?  I was able to do the first step devtools::install_github("yduan004/drugbankR", force=TRUE)
but not after that.

>library(drugbankR)
Error: package or namespace load failed for ‘drugbankR’:
 .onLoad failed in loadNamespace() for 'org.Hs.eg.db', details:
  call: l$contains
  error: $ operator is invalid for atomic vectors

**Comment by yduan004** [comment]
Hi, sorry for replying to you late. I just saw it.. It seems that you also need to install the `org.Hs.eg.db` package. You could refer to the package landing page at https://bioconductor.org/packages/release/data/annotation/html/org.Hs.eg.db.html. Please feel free to emal me or comment here if it doesn't solve your issue. Thanks!
